export const SAVE_FOOD_REQUEST = 'SAVE_FOOD_REQUEST';
export const FETCH_FOOD_REQUEST = 'FETCH_FOOD_REQUEST';
export const UPDATE_FOOD_REQUEST = 'UPDATE_FOOD_REQUEST';
export const DELETE_FOOD_REQUEST = 'DELETE_FOOD_REQUEST';
export const FOOD_SUCCESS = 'FOOD_SUCCESS';
export const FOOD_FAILURE = 'FOOD_FAILURE';